image:
  file: .gitpod.Dockerfile

tasks:
  # Check for pipenv command and configuration files
  - init: |
      command -v pipenv >/dev/null 2>&1 && {
        if [ ! -f Pipfile ]; then
          echo "No Pipfile found"
          if [ ! -f requirements.txt ]; then
            echo "No requirements.txt file found";
          else
            pipenv install -r requirements.txt;
          fi
        else
          yes | pipenv install;
        fi
      }
    # Check for PipFile
    command: |
      if [ ! -f Pipfile ]; then echo 'Run "pipenv --three"'; fi

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - ms-python.python
    - njpwerner.autodocstring
    - KevinRose.vsc-python-indent
    - formulahendry.code-runner
